export const data = [
    {
        question: "What is the function of a router in a computer network?",
        option1: "a) Connects multiple devices within the same local network",
        option2: "b) Determines the best path for data packets to reach their destination across different networks",
        option3: "c) Translates domain names into IP addresses",
        option4: "d) Establishes a secure connection between client and server",
        ans: 2,
    },
    {
        question: "Which protocol is used for sending and receiving email messages?",
        option1: "a) FTP (File Transfer Protocol)",
        option2: "b) SMTP (Simple Mail Transfer Protocol)",
        option3: "c) HTTP (Hypertext Transfer Protocol)",
        option4: "d) SSH (Secure Shell)",
        ans: 2,
    },
    {
        question: "What is the purpose of ARP (Address Resolution Protocol) in computer networking?",
        option1: "a) To map IP addresses to MAC addresses",
        option2: "b) To establish a secure connection between client and server",
        option3: "c) To route data packets between different networks",
        option4: "d) To encrypt data during transmission",
        ans: 1,
    },
    {
        question: "What is the main function of DNS (Domain Name System)?",
        option1: "a) To encrypt data during transmission",
        option2: "b) To convert IP addresses into domain names",
        option3: "c) To manage network traffic and congestion",
        option4: "d) To translate domain names into IP addresses",
        ans: 4,
    },
    {
        question: "Which networking device operates at the Data Link Layer of the OSI model?",
        option1: "a) Switch",
        option2: "b) Router",
        option3: "c) Hub",
        option4: "d) Repeater",
        ans: 1,
    },
    {
        question: "What is the purpose of NAT (Network Address Translation) in computer networking?",
        option1: "a) To secure data transmission over public networks",
        option2: "b) To assign IP addresses dynamically to devices on a network",
        option3: "c) To translate private IP addresses into public IP addresses",
        option4: "d) To authenticate users before granting network access",
        ans: 3,
    },
    {
        question: "Which networking protocol is used for securely accessing remote servers over an unsecured network?",
        option1: "a) HTTP",
        option2: "b) FTP",
        option3: "c) SSH (Secure Shell)",
        option4: "d) Telnet",
        ans: 3,
    },
    {
        question: "What is the purpose of a firewall in computer networking?",
        option1: "a) To connect multiple devices within the same local network",
        option2: "b) To filter incoming and outgoing network traffic based on predefined security rules",
        option3: "c) To translate domain names into IP addresses",
        option4: "d) To establish a secure connection between client and server",
        ans: 2,
    },
    {
        question: "What is the maximum transmission unit (MTU) in networking?",
        option1: "a) The maximum bandwidth of a network connection",
        option2: "b) The maximum number of devices that can be connected to a network",
        option3: "c) The maximum size of a data packet that can be transmitted over a network",
        option4: "d) The maximum distance between two network devices",
        ans: 3,
    },
    {
        question: "Which protocol is used for transferring files over the internet?",
        option1: "a) SMTP",
        option2: "b) FTP (File Transfer Protocol)",
        option3: "c) DNS",
        option4: "d) DHCP",
        ans: 2,
    },
    {
        question: "What is the role of the operating system?",
        option1: "a) Managing hardware resources",
        option2: "b) Running application software",
        option3: "c) Providing user interfaces",
        option4: "d) All of the above",
        ans: 4,
    },
    {
        question: "What is virtual memory?",
        option1: "a) Memory allocated for virtual machines",
        option2: "b) A memory management technique that uses disk space to extend RAM",
        option3: "c) Memory reserved for system processes",
        option4: "d) Memory used for storing data temporarily",
        ans: 2,
    },
    {
        question: "What is the purpose of a scheduler in an operating system?",
        option1: "a) To manage communication between hardware devices",
        option2: "b) To allocate system resources to running processes",
        option3: "c) To translate high-level programming languages into machine code",
        option4: "d) To encrypt data during transmission",
        ans: 2,
    },
    {
        question: "What is the difference between multi-tasking and multi-processing?",
        option1: "a) Multitasking refers to running multiple applications simultaneously, while multiprocessing refers to executing multiple threads within the same process",
        option2: "b) Multitasking refers to executing multiple threads within the same process, while multiprocessing refers to running multiple applications simultaneously",
        option3: "c) Multitasking and multiprocessing are the same thing",
        option4: "d) Multitasking refers to managing system resources, while multiprocessing refers to managing user tasks",
        ans: 1,
    },
    {
        question: "What is a deadlock in operating systems?",
        option1: "a) A situation where two or more processes are unable to proceed because each is waiting for the other to release a resource",
        option2: "b) A memory management error caused by accessing invalid memory addresses",
        option3: "c) A type of virus that spreads rapidly through a computer network",
        option4: "d) A hardware failure that results in data loss",
        ans: 1,
    },
    {
        question: "What is the purpose of a file system?",
        option1: "a) To manage communication between hardware devices",
        option2: "b) To allocate system resources to running processes",
        option3: "c) To organize and store data on storage devices",
        option4: "d) To translate high-level programming languages into machine code",
        ans: 3,
    },
    {
        question: "What is the kernel of an operating system?",
        option1: "a) The user interface of the operating system",
        option2: "b) The central component responsible for managing hardware resources",
        option3: "c) A type of system utility used for disk maintenance",
        option4: "d) The graphical representation of file structures on a storage device",
        ans: 2,
    },
    {
        question: "What is the purpose of a file system?",
        option1: "a) To manage communication between hardware devices",
        option2: "b) To allocate system resources to running processes",
        option3: "c) To organize and store data on storage devices",
        option4: "d) To translate high-level programming languages into machine code",
        ans: 3,
    },
    {
        question: "What is the kernel of an operating system?",
        option1: "a) The user interface of the operating system",
        option2: "b) The central component responsible for managing hardware resources",
        option3: "c) A type of system utility used for disk maintenance",
        option4: "d) The graphical representation of file structures on a storage device",
        ans: 2,
    },
    {
        question: "What is a system call in operating systems?",
        option1: "a) A function provided by the operating system for interacting with hardware devices",
        option2: "b) A type of virus that infects the boot sector of a storage device",
        option3: "c) A method for launching applications on a computer system",
        option4: "d) A tool used for monitoring system performance",
        ans: 1,
    },
    {
        question: "What is the purpose of device drivers in an operating system?",
        option1: "a) To manage communication between hardware devices",
        option2: "b) To allocate system resources to running processes",
        option3: "c) To provide a graphical user interface for interacting with the system",
        option4: "d) To translate high-level programming languages into machine code",
        ans: 1,
    },
    {
        question: "What is a database?",
        option1: "a) A collection of programs for managing computer hardware resources",
        option2: "b) A collection of data organized in a structured manner",
        option3: "c) A graphical representation of file structures on a storage device",
        option4: "d) A type of network protocol used for secure communication",
        ans: 2,
    },
    {
        question: "What is the purpose of a DBMS (Database Management System)?",
        option1: "a) To manage communication between hardware devices",
        option2: "b) To allocate system resources to running processes",
        option3: "c) To provide an interface for users to interact with the database",
        option4: "d) To translate high-level programming languages into machine code",
        ans: 3,
    },
    {
        question: "What is SQL (Structured Query Language)?",
        option1: "a) A programming language for developing web applications",
        option2: "b) A markup language for defining the structure of web pages",
        option3: "c) A language used for interacting with databases",
        option4: "d) A scripting language for automating tasks in operating systems",
        ans: 3,
    },
    {
        question: "What is normalization in the context of database design?",
        option1: "a) The process of converting data into a more efficient storage format",
        option2: "b) The process of organizing data into tables and columns",
        option3: "c) The process of removing redundancy and dependency from database tables",
        option4: "d) The process of encrypting sensitive data to protect it from unauthorized access",
        ans: 3,
    },
    {
        question: "What is a primary key in a database table?",
        option1: "a) A unique identifier for each record in the table",
        option2: "b) A foreign key referencing another table",
        option3: "c) A column that stores null values",
        option4: "d) A constraint that enforces data integrity rules",
        ans: 1,
    },
    {
        question: "What is a relational database?",
        option1: "a) A database that stores data in the form of tables and columns",
        option2: "b) A database that stores data in a hierarchical structure",
        option3: "c) A database that uses pointers to navigate between records",
        option4: "d) A database that stores data in unstructured format",
        ans: 1,
    },
    {
        question: "What is the purpose of an index in a database?",
        option1: "a) To encrypt sensitive data to protect it from unauthorized access",
        option2: "b) To improve the speed of data retrieval operations",
        option3: "c) To enforce data integrity rules",
        option4: "d) To organize data into tables and columns",
        ans: 2,
    },
    {
        question: "What is a transaction in the context of database management?",
        option1: "a) A unit of work performed by a database",
        option2: "b) A query used to retrieve data from a database",
        option3: "c) A language used for interacting with databases",
        option4: "d) A constraint that enforces data integrity rules",
        ans: 1,
    },
    {
        question: "What is the purpose of ACID properties in database transactions?",
        option1: "a) To ensure that transactions are executed in a consistent and reliable manner",
        option2: "b) To improve the performance of database operations",
        option3: "c) To enforce data integrity rules",
        option4: "d) To organize data into tables and columns",
        ans: 1,
    },
    {
        question: "What is a foreign key in the context of database management?",
        option1: "a) A unique identifier for each record in the table",
        option2: "b) A primary key referencing another table",
        option3: "c) A column that stores null values",
        option4: "d) A constraint that enforces data integrity rules",
        ans: 2,
    }

];
